### ISSUE TITLE
Select and implement SSR multi-thread solution

### ISSUE THREAD

**Issue by espen42** [enonic/lib-react4xp#191]
The following applies to code _updates that haven't been released yet,_ that fixed error handling and lock-ups, made the engine initialization threadsafe, and made it possible to research _this_ issue.

**Problem:** When multiple SSR rendering calls use the same (cached) dependencies at the same time, different java threads are used but with the same Nashorn engine instance. Different errors occur unpredictably, apparently when the threads make the engine concurrently use the same memory-space and values in the engine. #176 

This _only_ happens on concurrent rendering - when refreshing one page at a time, they always render fine. So error lock-up is fixed.

**Conclusion:** Rendering is not thread-safe. Possibly reactDOMServer itself is made to render in a single-thread environment (node), and was never made to be thread-safe? Nashorn breaks this paradigm.

**Solution candidates:**
- [x] Nashorn engine pool: rendering requests will select one of multiple available engines. 
    🥶 More complex to implement
    🥶 Untested
    🥶 Will multiply demands to memory and CPU (and engines will linger in memory!), 
    🥶 Initialization will be slower, 
    ➕ ...but will use the server much more efficiently

**Variants over the engine pool solution** (all of these: select one from the pool if an engine is available, wait if not):
- [x] When non-lazy-loading: all engines initialize all assets (nashornpolyfills, externals, vendors, chunks and entries) simultaneously and all become available after that. 
    🥶 Slow app start, no matter which component is rendered. 
    🥶 Hogs max resources immediately 
    ➕ Only done once, on each app start, and after that all engines fire on all cylinders, 
    ➕ Predictable behavior 
    ➕ Easiest engine pool variant to implement
- [x] When lazy-loading: reuse initialized engine if available. If only non-initialized engines are available, select one and base-initialize it (only load nashornpolyfills and externals. And vendors? Probably not, they should be part of the chunks dependency detection). It will remain initialized, and handles its own lazy-loading and caching after that.
    🥶 More complex 
    🥶 Slight but unpredictable variation in first-rendering performance. 
    ➕ Kindest resource use.

**Rejected:**
- ❌ Synchronize the rendering in java: only one rendering process can start and finish at the same time. 
    ➕ Easy to implement
    ➕ Kind to memory
    ➕ "fast" engine initialization: least nashorn warm-up time
    ❌ ...but **will hamper performance too much to be viable** since only one thread can be used at a time.

- ❌ SSR tied-in more closely with existing rendering in XP, benefitting from existing thread handling?

- ❌ Hybrid "chain" approach: When non-lazy-loading, engines are fully initialized with all assets, one engine after another - so the first engine is available earlier and rendering can start when other engines are still firing up. When lazy-loading, engines are still base-initialized one after another. After that, each engine is available, and handles its own lazy-loading and caching. 
    🥶 The most complex implementation
    ➕ Probably the sweet spot between fast warm-up time and later performance.

- ❌ Possibility: each rendering request looks for an available engine that has rendered the same entry before, so as to minimize excess asset lazy-loading (but will select an available, initialized engine if none of the available ones have rendered that entry before).

**Comment by sigdestad** [comment]
One thing is sure, you cannot use syncronized!

**Comment by espen42** [comment]
Conclusion: expand existing solution with engine pool. Aim for [apache pool](http://commons.apache.org/proper/commons-pool/apidocs/index.html) based solution that reuses available engines if possioble.
