### ISSUE TITLE
Support for webpack 5.x and webpack-cli 4.x

### ISSUE THREAD

**Issue by doubleness** [enonic/lib-react4xp#223]
Hey, I am trying to use react4xp in our existing project, where we are running `webpack 5.16.0` and `webpack-cli 4.7.2`

I am getting following error during build:
```
> Task :react4xp_components FAILED
[webpack-cli] Error: Unknown option '--env.VERBOSE=false'
[webpack-cli] Run 'webpack --help' to see available commands and options

FAILURE: Build failed with an exception.
```
I was able to replicate same issue in https://github.com/enonic/starter-react4xp by upgrading webpack and enonic-cli to mentioned versions and running `gradle build`.

Any ideas how I could get this to work?

**Comment by espen42** [comment]
I'm trying this in the starter, to keep it minimal. I'm getting a different error:

```
[webpack-cli] SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid escape
```

According to what I've found out so far, this is connected to specific versions of webpack, webpack-cli and node.js - and I'm testing the webpack/-cli versions mentioned above. What version of node.js are you using?

**Comment by espen42** [comment]
Preliminary findings, making headway toward a solution, but not quite there yet:

- [ ] In build.gradle:
    - `id "com.github.node-gradle.node" version "3.0.1"` works better than the mooworks node plugin.
    - Add this block under the end of the `dependencies` block:
    ```
		node {
		    version = '12.22.4'
		    download = true
		}
    ```
    - Change `apply from: react4xpGradlePath` to `apply from: 'react4xp.gradle'` (see below)
    
- [ ] In node_modules/react4xp/react4xp.gradle
    - Copy react4xp.gradle to project root
    - Changes in the copy:
        - All CLI instances of `--env.X=Y` must replace the period with a space: `--env X=Y`. In the `args` array syntax they must be split in two strings: `'--env', 'X=Y'`
        - And for the conditional (config-dependent) extra arguments, `+=` won't cut it anymore. Instead of `args += '--env.X=Y'`, use `args.addAll[('--env', 'X=Y'])`

- [ ] Also changes to _node_modules/react4xp-build-components/webpack.config.js_ (which will be overwritten when reinstalling npm, so this must be kept up to date until a new release of _react4xp-build-components_):
    - In the output webpack-config object at the end, `query` should now be `options`

Proceeding from here: react compilation errors. Webpack doesn't seem to resolve secondary dependencies correctly:
```
ERROR in ./node_modules/react4xp-regions/entries/react4xp-regions/Layout.jsx 1:25-59
Module not found: Error: Can't resolve 'prop-types' in '/Users/espenjobb/source/xp7/apps/temp/react4xp3test/node_modules/react4xp-regions/entries/react4xp-regions'

ERROR in ./node_modules/react4xp-regions/entries/react4xp-regions/Layout.jsx 1:59-105
Module not found: Error: Can't resolve 'react4xp-regions/Regions' in '/Users/espenjobb/source/xp7/apps/temp/react4xp3test/node_modules/react4xp-regions/entries/react4xp-regions'

ERROR in ./node_modules/react4xp-regions/entries/react4xp-regions/Page.jsx 1:25-59
Module not found: Error: Can't resolve 'prop-types' in '/Users/espenjobb/source/xp7/apps/temp/react4xp3test/node_modules/react4xp-regions/entries/react4xp-regions'

ERROR in ./node_modules/react4xp-regions/entries/react4xp-regions/Page.jsx 1:59-105
Module not found: Error: Can't resolve 'react4xp-regions/Regions' in '/Users/espenjobb/source/xp7/apps/temp/react4xp3test/node_modules/react4xp-regions/entries/react4xp-regions'

ERROR in ./src/main/resources/site/pages/default/default.jsx 1:97-143
Module not found: Error: Can't resolve 'react4xp-regions/Regions' in '/Users/espenjobb/source/xp7/apps/temp/react4xp3test/src/main/resources/site/pages/default'
```

**Comment by espen42** [comment]
The react compilation errors was due to a faulty project-rootpath resolution. Proceeding with next obstacles.

**Comment by espen42** [comment]
Looking for a workaround for [this webpack5 bug](https://github.com/webpack/webpack/issues/9297), specifically how to get `chunkFilename` to work as before with `[contenthash:9]` or at least `[contenthash]`. Or some other way to name the built chunks uniquely and content-dependently.

Example fromwebpack config for the build-components step:
```
...,
output": {
    ...,
    "filename": "[name].js",
    "chunkFilename": "[name].[contenthash].js",
    "libraryTarget": "var",
    "library": [
      "React4xp",
      "[name]"
    ]
  },
...
```

**Comment by espen42** [comment]
Next: stats.component.json output has a different structure now. 

Instead of...

```
  "entrypoints": {
    "site/pages/default/default": {
      ...,
      "assets": [
        "vendors.ea7445b19.js",
        "vendors.ea7445b19.js.map",
        "templates.918bb16c3.js",
        "templates.918bb16c3.js.map",
        "site/pages/default/default.js"
        "site/pages/default/default.js.map"
      ],
```

...now the same might look like:

```
  "entrypoints": {
    "site/pages/default/default": {
      ...,
      "assets": [
        { "name": "vendors.ea7445b19.js", "size": 1234 },
        { "name": "templates.918bb16c3.js", "size": 1234 },
        { "name": "site/pages/default/default.js", "size": 1234 }
      ],
    "auxiliaryAssets": [
        { "name": "vendors.ea7445b19.js.map", "size": 1234 },
        { "name": "templates.918bb16c3.js.map", "size": 1234 },
        { "name": "site/pages/default/default.js.map", "size": 1234 }
      ],
```

This causes lib-react4xp error at runtime (`asset.endsWith is not a function`).

Adapt lib-react4xp? Or maybe _stats-webpack-plugin_ can be configured?

**Comment by espen42** [comment]
Flawed compilation? Compiled react components end up with structures like `this.webpackChunkReact4xp_name_`, where `this` is undefined - at least when running in nashorn.

**Comment by espen42** [comment]
A lot of things were breaking when upgrading the whole react4xp suite to webpack 5. But first successful rendering happened locally just now. ⭐ 

Testing a bit more, then probably releasing react4xp v2 soon.

**Comment by espen42** [comment]
There we go! Works locally now, I have unofficially released version **2.0.0-RC2** of both the [NPM package](https://www.npmjs.com/package/react4xp) and [the library](https://repo.enonic.com/public/com/enonic/lib/lib-react4xp/). 

I would love it if anyone is interested in taking it for a spin in your own project(s) and tell me how it works for you! :) 

Should be as easy as:
- Update version of both lib-react4xp in build.gradle and react4xp in package.json, to 2.0.0-RC2.
- Update webpack to 5.x.x, and webpack-cli to 4.x.x.
- Best clean up known caches, wipe the <project>/build and /node_modules and so on, 
- Rebuild/deploy.

**Comment by espen42** [comment]
https://discuss.enonic.com/t/react4xp-release-2-0-0/2577
